"""review status to assignments

Revision ID: 8137239a23f1
Revises: 1a37a84fc277
Create Date: 2024-05-11 18:31:33.022516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8137239a23f1'
down_revision = '1a37a84fc277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
